//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sims2023.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sims2023.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted requests:.
        /// </summary>
        internal static string acceptedRequestsLabel {
            get {
                return ResourceManager.GetString("acceptedRequestsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string acceptedTitle {
            get {
                return ResourceManager.GetString("acceptedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string activateBtn {
            get {
                return ResourceManager.GetString("activateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string addBtn {
            get {
                return ResourceManager.GetString("addBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add pictures:.
        /// </summary>
        internal static string addPicturesLabel {
            get {
                return ResourceManager.GetString("addPicturesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tours.
        /// </summary>
        internal static string allToursMenu {
            get {
                return ResourceManager.GetString("allToursMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string availableData {
            get {
                return ResourceManager.GetString("availableData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average number of guests in accepted requests:.
        /// </summary>
        internal static string averageNumberLabel {
            get {
                return ResourceManager.GetString("averageNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string backBtn {
            get {
                return ResourceManager.GetString("backBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancelBtn {
            get {
                return ResourceManager.GetString("cancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string cityData {
            get {
                return ResourceManager.GetString("cityData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string cityLabel {
            get {
                return ResourceManager.GetString("cityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex tour request.
        /// </summary>
        internal static string complexTourRequestMenu {
            get {
                return ResourceManager.GetString("complexTourRequestMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string countryData {
            get {
                return ResourceManager.GetString("countryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        internal static string countryLabel {
            get {
                return ResourceManager.GetString("countryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string createBtn {
            get {
                return ResourceManager.GetString("createBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string createdData {
            get {
                return ResourceManager.GetString("createdData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declined.
        /// </summary>
        internal static string declinedTitle {
            get {
                return ResourceManager.GetString("declinedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string descriptionData {
            get {
                return ResourceManager.GetString("descriptionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string descriptionLabel {
            get {
                return ResourceManager.GetString("descriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string durationData {
            get {
                return ResourceManager.GetString("durationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (in hours):.
        /// </summary>
        internal static string durationLabel {
            get {
                return ResourceManager.GetString("durationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        internal static string endDateData {
            get {
                return ResourceManager.GetString("endDateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date:.
        /// </summary>
        internal static string endDateLabel {
            get {
                return ResourceManager.GetString("endDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string englishMenu {
            get {
                return ResourceManager.GetString("englishMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiring.
        /// </summary>
        internal static string expiringData {
            get {
                return ResourceManager.GetString("expiringData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your tour.
        /// </summary>
        internal static string findYourTourTitle {
            get {
                return ResourceManager.GetString("findYourTourTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide&apos;s language capabilility:.
        /// </summary>
        internal static string gudiesLanguageCapabilityLabel {
            get {
                return ResourceManager.GetString("gudiesLanguageCapabilityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of guests:.
        /// </summary>
        internal static string guestNumberLabel {
            get {
                return ResourceManager.GetString("guestNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests.
        /// </summary>
        internal static string guestsData {
            get {
                return ResourceManager.GetString("guestsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide&apos;s Knowledge:.
        /// </summary>
        internal static string guidesKnowledgeLabel {
            get {
                return ResourceManager.GetString("guidesKnowledgeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string homeMenu {
            get {
                return ResourceManager.GetString("homeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string hoursData {
            get {
                return ResourceManager.GetString("hoursData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours:.
        /// </summary>
        internal static string hoursLabel {
            get {
                return ResourceManager.GetString("hoursLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest of tour:.
        /// </summary>
        internal static string interestOfTourLabel {
            get {
                return ResourceManager.GetString("interestOfTourLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        internal static string joinBtn {
            get {
                return ResourceManager.GetString("joinBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key point:.
        /// </summary>
        internal static string keyPointLabel {
            get {
                return ResourceManager.GetString("keyPointLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string languageData {
            get {
                return ResourceManager.GetString("languageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string languageLabel {
            get {
                return ResourceManager.GetString("languageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string languagesTitle {
            get {
                return ResourceManager.GetString("languagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a comment:.
        /// </summary>
        internal static string leaveACommentLabel {
            get {
                return ResourceManager.GetString("leaveACommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live tracking tour.
        /// </summary>
        internal static string liveTrackingTourLabel {
            get {
                return ResourceManager.GetString("liveTrackingTourLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string logoutMenu {
            get {
                return ResourceManager.GetString("logoutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max guests.
        /// </summary>
        internal static string maxGuestsData {
            get {
                return ResourceManager.GetString("maxGuestsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My complex tour requests.
        /// </summary>
        internal static string myComplexTourRequestsLabel {
            get {
                return ResourceManager.GetString("myComplexTourRequestsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My coupons.
        /// </summary>
        internal static string myCouponsMenu {
            get {
                return ResourceManager.GetString("myCouponsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My tour requests.
        /// </summary>
        internal static string myTourRequestsLabel {
            get {
                return ResourceManager.GetString("myTourRequestsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My tours.
        /// </summary>
        internal static string myToursMenu {
            get {
                return ResourceManager.GetString("myToursMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string nameData {
            get {
                return ResourceManager.GetString("nameData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string nameLabel {
            get {
                return ResourceManager.GetString("nameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New request.
        /// </summary>
        internal static string newRequestBtn {
            get {
                return ResourceManager.GetString("newRequestBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New subtour.
        /// </summary>
        internal static string newSubtourBtn {
            get {
                return ResourceManager.GetString("newSubtourBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New subtour request.
        /// </summary>
        internal static string newSubtourRequestLabel {
            get {
                return ResourceManager.GetString("newSubtourRequestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tour request.
        /// </summary>
        internal static string newTourRequestLabel {
            get {
                return ResourceManager.GetString("newTourRequestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not accepted requests:.
        /// </summary>
        internal static string notAcceptedRequestsLabel {
            get {
                return ResourceManager.GetString("notAcceptedRequestsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string notificationsMenu {
            get {
                return ResourceManager.GetString("notificationsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of people:.
        /// </summary>
        internal static string peopleNumberLabel {
            get {
                return ResourceManager.GetString("peopleNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string rateBtn {
            get {
                return ResourceManager.GetString("rateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string reportLabel {
            get {
                return ResourceManager.GetString("reportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string reportMenu {
            get {
                return ResourceManager.GetString("reportMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of requests.
        /// </summary>
        internal static string requestNumberTitle {
            get {
                return ResourceManager.GetString("requestNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve.
        /// </summary>
        internal static string reserveBtn {
            get {
                return ResourceManager.GetString("reserveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved for.
        /// </summary>
        internal static string reservedForData {
            get {
                return ResourceManager.GetString("reservedForData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string searchBtn {
            get {
                return ResourceManager.GetString("searchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        internal static string seeMoreBtn {
            get {
                return ResourceManager.GetString("seeMoreBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string sendBtn {
            get {
                return ResourceManager.GetString("sendBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        internal static string serbianMenu {
            get {
                return ResourceManager.GetString("serbianMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string showBtn {
            get {
                return ResourceManager.GetString("showBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string skipBtn {
            get {
                return ResourceManager.GetString("skipBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string startDateData {
            get {
                return ResourceManager.GetString("startDateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date:.
        /// </summary>
        internal static string startDateLabel {
            get {
                return ResourceManager.GetString("startDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        internal static string startTimeData {
            get {
                return ResourceManager.GetString("startTimeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time:.
        /// </summary>
        internal static string startTimeLabel {
            get {
                return ResourceManager.GetString("startTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string stateData {
            get {
                return ResourceManager.GetString("stateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string statisticsBtn {
            get {
                return ResourceManager.GetString("statisticsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics on accepted tours.
        /// </summary>
        internal static string statisticsOnAcceptedToursTab {
            get {
                return ResourceManager.GetString("statisticsOnAcceptedToursTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtours.
        /// </summary>
        internal static string subtoursData {
            get {
                return ResourceManager.GetString("subtoursData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string themeMenu {
            get {
                return ResourceManager.GetString("themeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string timeTitle {
            get {
                return ResourceManager.GetString("timeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour&apos;s details.
        /// </summary>
        internal static string tourDetailsLabel {
            get {
                return ResourceManager.GetString("tourDetailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour request.
        /// </summary>
        internal static string tourRequestMenu {
            get {
                return ResourceManager.GetString("tourRequestMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour request&apos;s statistics for language.
        /// </summary>
        internal static string tourRequestsStatisticsForLanguageTab {
            get {
                return ResourceManager.GetString("tourRequestsStatisticsForLanguageTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour request&apos;s statistics for location .
        /// </summary>
        internal static string tourRequestsStatisticsForLocationTab {
            get {
                return ResourceManager.GetString("tourRequestsStatisticsForLocationTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string welcomeText {
            get {
                return ResourceManager.GetString("welcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year:.
        /// </summary>
        internal static string yearLabel {
            get {
                return ResourceManager.GetString("yearLabel", resourceCulture);
            }
        }
    }
}
